favicon: null
name: elliottpayne
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.443072
  brandStrength: 0.6868958
  lightness: 0.3356606
  brandColors:
    - '#1B1C20'
    - '#67A9F5'
    - '#5480BD'
    - '#95A655'
    - '#C7E1F8'
  rhythmicContrast: 0
typography_spectrum: 0.34624
layout_spectrum: 0.349624
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
