layout_spectrum: 0.8618283802643418
typography_spectrum: 0.6377285497728735
color:
  saturation: 0.6594462767243385
  brandStrength: 0.4338183617219329
  lightness: 0.7223887129221112
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.8854787957388908
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: elliottpayne
